In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("./cancer.csv")

In [3]:
op = df["diagnosis"]

In [4]:
df = df.drop(["diagnosis","id","Unnamed: 32"],axis=1)

In [5]:
X = df.values

In [6]:
y = op.values

In [7]:
lab = LabelEncoder()
lab.fit(y)

LabelEncoder()

In [8]:
y_lab = lab.transform(y)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y_lab)

In [20]:
clf = LogisticRegression(solver='newton-cg')

In [21]:
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='newton-cg', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
y_pred = clf.predict(X_test)

In [23]:
X_test[3]

array([1.396e+01, 1.705e+01, 9.143e+01, 6.024e+02, 1.096e-01, 1.279e-01,
       9.789e-02, 5.246e-02, 1.908e-01, 6.130e-02, 4.250e-01, 8.098e-01,
       2.563e+00, 3.574e+01, 6.351e-03, 2.679e-02, 3.119e-02, 1.342e-02,
       2.062e-02, 2.695e-03, 1.639e+01, 2.207e+01, 1.081e+02, 8.260e+02,
       1.512e-01, 3.262e-01, 3.209e-01, 1.374e-01, 3.068e-01, 7.957e-02])

In [24]:
clf.predict([X_test[3]])[0]

0

In [25]:
y_test[3]

1

In [26]:
y_test

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1])

In [27]:
y_pred

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0])

In [28]:
accuracy_score(y_pred,y_test)

0.972027972027972

In [29]:
confusion_matrix(y_pred,y_test)

array([[82,  4],
       [ 0, 57]])